
package websvr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param deviceCode
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetGarrison", action = "http://tempuri.org/IService/SetGarrison")
    @WebResult(name = "SetGarrisonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetGarrison", targetNamespace = "http://tempuri.org/", className = "websvr.SetGarrison")
    @ResponseWrapper(localName = "SetGarrisonResponse", targetNamespace = "http://tempuri.org/", className = "websvr.SetGarrisonResponse")
    public Boolean setGarrison(
        @WebParam(name = "DeviceCode", targetNamespace = "http://tempuri.org/")
        String deviceCode);

    /**
     * 
     * @param deviceCode
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetDisarm", action = "http://tempuri.org/IService/SetDisarm")
    @WebResult(name = "SetDisarmResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetDisarm", targetNamespace = "http://tempuri.org/", className = "websvr.SetDisarm")
    @ResponseWrapper(localName = "SetDisarmResponse", targetNamespace = "http://tempuri.org/", className = "websvr.SetDisarmResponse")
    public Boolean setDisarm(
        @WebParam(name = "DeviceCode", targetNamespace = "http://tempuri.org/")
        String deviceCode);

    /**
     * 
     * @param deviceCode
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetSolved", action = "http://tempuri.org/IService/SetSolved")
    @WebResult(name = "SetSolvedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetSolved", targetNamespace = "http://tempuri.org/", className = "websvr.SetSolved")
    @ResponseWrapper(localName = "SetSolvedResponse", targetNamespace = "http://tempuri.org/", className = "websvr.SetSolvedResponse")
    public Boolean setSolved(
        @WebParam(name = "DeviceCode", targetNamespace = "http://tempuri.org/")
        String deviceCode);

    /**
     * 
     * @param deviceCode
     * @param n
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetElectrical", action = "http://tempuri.org/IService/SetElectrical")
    @WebResult(name = "SetElectricalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetElectrical", targetNamespace = "http://tempuri.org/", className = "websvr.SetElectrical")
    @ResponseWrapper(localName = "SetElectricalResponse", targetNamespace = "http://tempuri.org/", className = "websvr.SetElectricalResponse")
    public Boolean setElectrical(
        @WebParam(name = "DeviceCode", targetNamespace = "http://tempuri.org/")
        String deviceCode,
        @WebParam(name = "N", targetNamespace = "http://tempuri.org/")
        String n);

}
